# Generated by Django 6.0.5 on 2026-06-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonnaroo', '0002_sharedlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlocation',
            name='tag',
            field=models.CharField(blank=True, choices=[('', 'None'), ('food', 'Food'), ('water', 'Water'), ('stage', 'Stage'), ('bathroom', 'Bathroom')], default='', max_length=20),
        ),
    ]
