# Generated by Django 6.0.5 on 2026-08-22 03:25

import django.db.models.deletion
import django.utils.timezone
import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('work_authorized', models.BooleanField(default=True)),
                ('needs_sponsorship', models.BooleanField(default=False)),
                ('salary_expectation', models.CharField(blank=True, default='', max_length=100)),
                ('notice_period', models.CharField(blank=True, default='', max_length=100)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('preferred_locations', models.JSONField(blank=True, default=jobs.models._list)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('github_url', models.URLField(blank=True, default='')),
                ('portfolio_url', models.URLField(blank=True, default='')),
                ('references_note', models.TextField(blank=True, default='')),
                ('eeo_answers', models.JSONField(blank=True, default=jobs.models._dict)),
                ('extra_answers', models.JSONField(blank=True, default=jobs.models._dict, help_text='Freeform question -> answer bank the autofill draws from.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigestSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('new_job_count', models.IntegerField(default=0)),
                ('applied_count', models.IntegerField(default=0)),
                ('skipped', models.BooleanField(default=False)),
                ('skip_reason', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('alt_urls', models.JSONField(blank=True, default=jobs.models._list, help_text='Other boards listing the same role, found during dedupe.')),
                ('dedupe_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('is_remote', models.BooleanField(default=False)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('description_html', models.TextField(blank=True, default='')),
                ('description_text', models.TextField(blank=True, default='')),
                ('raw', models.JSONField(blank=True, default=jobs.models._dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('filtered', 'Filtered out'), ('scored', 'Scored'), ('shortlisted', 'Shortlisted'), ('prepped', 'Prepped'), ('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('dismissed', 'Dismissed'), ('closed', 'Closed')], db_index=True, default='new', max_length=20)),
                ('filter_reason', models.CharField(blank=True, default='', help_text='Why tier 0 rejected this. Keeps the pre-filter auditable.', max_length=200)),
                ('discovered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('ashby', 'Ashby'), ('remotive', 'Remotive'), ('arbeitnow', 'Arbeitnow'), ('usajobs', 'USAJobs'), ('hn_hiring', 'HN Who Is Hiring'), ('adzuna', 'Adzuna'), ('jsearch', 'JSearch')], max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('config', models.JSONField(blank=True, default=jobs.models._dict, help_text='Adapter config (company slug, query params). Never secrets -- those come from env.')),
                ('enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('consecutive_failures', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['kind', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('sources_run', models.IntegerField(default=0)),
                ('found', models.IntegerField(default=0)),
                ('new', models.IntegerField(default=0)),
                ('filtered', models.IntegerField(default=0)),
                ('scored', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=jobs.models._list)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default search', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('titles', models.JSONField(blank=True, default=jobs.models._list, help_text='Case-insensitive substrings; a title matching none is rejected.')),
                ('title_exclusions', models.JSONField(blank=True, default=jobs.models._list)),
                ('locations', models.JSONField(blank=True, default=jobs.models._list, help_text='Case-insensitive substrings matched against posting location.')),
                ('remote_ok', models.BooleanField(default=True)),
                ('remote_only', models.BooleanField(default=False)),
                ('min_salary', models.IntegerField(blank=True, help_text='Rejects a posting only when it states a max below this. Unstated salary always passes.', null=True)),
                ('seniority_floor', models.CharField(blank=True, default='', max_length=20)),
                ('seniority_ceiling', models.CharField(blank=True, default='', max_length=20)),
                ('must_have', models.JSONField(blank=True, default=jobs.models._list)),
                ('nice_to_have', models.JSONField(blank=True, default=jobs.models._list)),
                ('exclude_keywords', models.JSONField(blank=True, default=jobs.models._list)),
                ('exclude_companies', models.JSONField(blank=True, default=jobs.models._list)),
                ('min_score_to_show', models.IntegerField(default=60)),
                ('tailoring_mode', models.CharField(choices=[('maximum', 'Maximum keyword optimization'), ('balanced', 'Balanced'), ('conservative', 'Supported claims only')], default='maximum', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs.jobposting')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='JobScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_score', models.IntegerField(db_index=True)),
                ('verdict', models.CharField(blank=True, default='', max_length=20)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('matched_keywords', models.JSONField(blank=True, default=jobs.models._list)),
                ('missing_keywords', models.JSONField(blank=True, default=jobs.models._list)),
                ('red_flags', models.JSONField(blank=True, default=jobs.models._list)),
                ('model_used', models.CharField(blank=True, default='', max_length=60)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('posting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='jobs.jobposting')),
            ],
        ),
        migrations.AddField(
            model_name='jobposting',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='jobs.jobsource'),
        ),
        migrations.CreateModel(
            name='TailoredApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('resume_json', models.JSONField(blank=True, default=jobs.models._dict)),
                ('cover_letter_md', models.TextField(blank=True, default='')),
                ('cover_letter_needed', models.BooleanField(default=True)),
                ('screener_answers', models.JSONField(blank=True, default=jobs.models._dict)),
                ('ats_keywords_used', models.JSONField(blank=True, default=jobs.models._list)),
                ('stretch_claims', models.JSONField(blank=True, default=jobs.models._list, help_text='Claims beyond the master resume. Surfaced as "Be ready to defend".')),
                ('model_used', models.CharField(blank=True, default='', max_length=60)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobposting')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['status', '-discovered_at'], name='jobs_jobpos_status_02de69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobposting',
            unique_together={('source', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='tailoredapplication',
            unique_together={('posting', 'version')},
        ),
    ]
