# Generated by Django 6.0.5 on 2026-08-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprofile',
            name='daily_application_target',
            field=models.IntegerField(default=15, help_text='Applications per day the funnel aims to supply.'),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='daily_inbox_size',
            field=models.IntegerField(default=25, help_text='How many scored jobs the inbox and digest surface per day.'),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='max_triage_per_run',
            field=models.IntegerField(default=80, help_text='Safety valve. Above this, the free keyword pre-rank picks which to score.'),
        ),
    ]
