# Generated by Django 6.0.5 on 2026-08-22 19:02

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_searchprofile_daily_application_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoredapplication',
            name='cover_letter_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tailoredapplication',
            name='cover_letter_original',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='extra_answers',
            field=models.JSONField(blank=True, default=jobs.models._dict, help_text='Freeform question -> answer bank the screener drafting draws from.'),
        ),
    ]
