# Generated by Django 6.0.5 on 2026-08-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, default='', max_length=160)),
                ('budget', models.CharField(blank=True, choices=[('', 'Not sure yet'), ('under-5k', 'Under $5,000'), ('5-15k', '$5,000 - $15,000'), ('15-40k', '$15,000 - $40,000'), ('40k-plus', '$40,000+'), ('retainer', 'Ongoing / retainer')], default='', max_length=20)),
                ('timeline', models.CharField(blank=True, choices=[('', 'No fixed date'), ('asap', 'As soon as possible'), ('1-month', 'Within a month'), ('quarter', 'This quarter'), ('exploring', 'Just exploring')], default='', max_length=20)),
                ('message', models.TextField()),
                ('source', models.CharField(blank=True, default='', help_text='Which call to action the visitor used.', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('contacted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
