# Generated by Django 5.0.1 on 2024-01-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='job_title',
        ),
        migrations.AddField(
            model_name='resume',
            name='current_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='desired_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
