# Generated by Django 5.0.1 on 2024-01-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_employmenthistory_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employmenthistory',
            old_name='position',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='employmenthistory',
            name='title',
        ),
    ]
