# Generated by Django 5.0.1 on 2024-01-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_rename_position_employmenthistory_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenthistory',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
