# Generated by Django 5.0.1 on 2024-01-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_rename_awards_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='description',
            field=models.TextField(default='nada'),
            preserve_default=False,
        ),
    ]
