# Generated by Django 5.0.1 on 2024-01-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_award_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
