# Generated by Django 5.0.1 on 2024-01-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_alter_award_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.TextField(blank=True),
        ),
    ]
