# Generated by Django 5.0.1 on 2024-01-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_resume_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.ManyToManyField(to='resume.education'),
        ),
    ]
