# Generated by Django 5.0.1 on 2024-01-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_education_remove_resume_education_resume_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
