# Generated by Django 5.0.1 on 2024-02-04 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_alter_employmenthistory_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employmenthistory',
            old_name='description',
            new_name='description_html',
        ),
        migrations.RenameField(
            model_name='professionalsummary',
            old_name='summary',
            new_name='summary_html',
        ),
    ]
