# Generated by Django 5.0.2 on 2024-05-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_keyword_resume_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenthistory',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
